import { AppComponent } from './components/AppComponent/AppComponent.js';
import { ContainerComponent } from './components/ContainerComponent/ContainerComponent.js';
import { NavBar } from './components/NavBar/NavBar.js';
import { TitleComponent } from './components/TitleComponent/TitleComponent.js';
import { TextComponent } from './components/TextComponent/TextComponent.js';
import { AccordionList } from './components/AccordionList/AccordionList.js';
import { AccordionItem } from './components/AccordionItem/AccordionItem.js';
import { CodeBlock } from './components/CodeBlock/CodeBlock.js';
import { IconChevron } from './components/IconChevron.js';
import { IconComponent } from './components/IconComponent.js';
import { IconHtml } from './components/IconHtml.js';
import { IconShadow } from './components/IconShadow.js';
import { DemoBox } from './components/DemoBox/DemoBox.js';

customElements.define('app-component', AppComponent);
customElements.define('container-component', ContainerComponent);
customElements.define('nav-bar', NavBar);
customElements.define('title-component', TitleComponent);
customElements.define('text-component', TextComponent);
customElements.define('accordion-list', AccordionList);
customElements.define('accordion-item', AccordionItem);
customElements.define('code-block', CodeBlock);
customElements.define('icon-chevron', IconChevron);
customElements.define('icon-component', IconComponent);
customElements.define('icon-html', IconHtml);
customElements.define('icon-shadow', IconShadow);
customElements.define('demo-box', DemoBox);
